language: python
cache:
  - apt
  - pip
python:
  - 2.7
notifications:
  email: false
 
# Setup anaconda
before_install:
  - sudo apt-get update
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - conda info -a
# Install packages
install:
  - conda env create && source activate test-environment
# Run test
script:
  - lettuce 
