name: exporter
dependencies:
- flask=0.10.1=py27_1
- itsdangerous=0.24=py27_0
- jinja2=2.7.3=py27_1
- markupsafe=0.23=py27_0
- nose=1.3.7=py27_0
- openssl=1.0.1k=1
- pip=7.0.3=py27_0
- python=2.7.10=0
- readline=6.2=2
- setuptools=17.0=py27_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- werkzeug=0.10.4=py27_0
- zlib=1.2.8=0
- pip:
  - argh==0.26.1
  - colorama==0.3.3
  - coverage==3.7.1
  - extras==0.0.3
  - flask-testing==0.4.2
  - fuzzywuzzy==0.5.0
  - lettuce==0.2.20
  - linecache2==1.0.0
  - mock==1.0.1
  - pathtools==0.1.2
  - pbr==1.1.1
  - python-coveralls==2.5.0
  - python-levenshtein==0.12.0
  - python-mimeparse==0.1.4
  - python-subunit==1.1.0
  - python-termstyle==0.1.10
  - pyyaml==3.11
  - rednose==0.4.3
  - requests==2.7.0
  - sh==1.11
  - six==1.9.0
  - sure==1.2.12
  - testtools==1.8.0
  - traceback2==1.4.0
  - unittest2==1.0.1
  - watchdog==0.8.3
