"""empty message

Revision ID: 1e5e51268b38
Revises: None
Create Date: 2015-06-20 21:24:54.278562

"""

# revision identifiers, used by Alembic.
revision = '1e5e51268b38'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('another_tableB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colA', sa.String(length=128), nullable=True),
    sa.Column('colB', sa.String(length=128), nullable=True),
    sa.Column('colC', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datatableC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colA', sa.String(length=128), nullable=True),
    sa.Column('colB', sa.String(length=128), nullable=True),
    sa.Column('colC', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tableA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colA', sa.String(length=128), nullable=True),
    sa.Column('colB', sa.String(length=128), nullable=True),
    sa.Column('colC', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tableA')
    op.drop_table('datatableC')
    op.drop_table('another_tableB')
    ### end Alembic commands ###
