"""empty message

Revision ID: 4279f914c6ce
Revises: None
Create Date: 2015-07-30 12:11:24.379389

"""

# revision identifiers, used by Alembic.
revision = '4279f914c6ce'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NCDC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colA', sa.String(length=128), nullable=True),
    sa.Column('colB', sa.String(length=128), nullable=True),
    sa.Column('colC', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('STATIONS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colA', sa.String(length=128), nullable=True),
    sa.Column('colB', sa.String(length=128), nullable=True),
    sa.Column('colC', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WEATHER',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('colA', sa.String(length=128), nullable=True),
    sa.Column('colB', sa.String(length=128), nullable=True),
    sa.Column('colC', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WEATHER')
    op.drop_table('STATIONS')
    op.drop_table('NCDC')
    ### end Alembic commands ###
