"""empty message

Revision ID: 95b9c6ad9d7
Revises: 4279f914c6ce
Create Date: 2015-07-31 11:51:10.488440

"""

# revision identifiers, used by Alembic.
revision = '95b9c6ad9d7'
down_revision = '4279f914c6ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
